apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-push
  namespace: argo-events
spec:
  eventBusName: default
  github:
    repo-push:
      repositories:
        - owner: dp-dev-test
          repo: experiments
      events:
        - push
      apiToken:
        name: github-access
        key: token
      webhook:
        endpoint: /push
        port: "12000"
      insecure: true
      active: true
      contentType: json
      filters:
        # Advanced script-based filtering
        script: |
          // For push events
          if (data.commits) {
            return data.commits.some(commit => 
              (commit.added && commit.added.some(file => /\.config$/.test(file))) ||
              (commit.modified && commit.modified.some(file => /\.config$/.test(file))) ||
              (commit.removed && commit.removed.some(file => /\.config$/.test(file)))
            );
          }
        