apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-push-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: github-push-dep
      eventSourceName: github-push
      eventName: repo-push
      filters:
        script: |
          -- Access the event body (the GitHub webhook payload)
          local payload = event.body

          -- Check if 'commits' array exists and iterate
          if payload and payload.commits then
              for _, commit in ipairs(payload.commits) do
                  -- Check added files
                  if commit.added then
                      for _, filepath in ipairs(commit.added) do
                          if type(filepath) == "string" and filepath:match("%.config$") then
                              print("Found a .config file in added files: " .. filepath)
                              return true -- Found a .config file, filter passes
                          end
                      end
                  end

                  -- Check modified files
                  if commit.modified then
                      for _, filepath in ipairs(commit.modified) do
                          if type(filepath) == "string" and filepath:match("%.config$") then
                              print("Found a .config file in modified files: " .. filepath)
                              return true -- Found a .config file, filter passes
                          end
                      end
                  end

                  -- Check removed files
                  if commit.removed then
                      for _, filepath in ipairs(commit.removed) do
                          if type(filepath) == "string" and filepath:match("%.config$") then
                              print("Found a .config file in removed files: " .. filepath)
                              return true -- Found a .config file, filter passes
                          end
                      end
                  end
              end
            print("No config files changes found in the payload")
            return false
          end
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: non-manifest-workflow-
              spec:
                entrypoint: main
                templates:
                  - name: main
                    container:
                      image: alpine:3.18
                      command: [echo]
                      args: ["Non-manifest file changes was triggered!!!"]