apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: weather-forecast-set
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: weather-forecast-dev
  template:
    metadata:
      name: 'weather-forecast-{{env}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/dp-dev-test/experiments.git'
        targetRevision: HEAD
        path: weather-forecast-argocd/manifests
      destination:
        server: 'https://docker-aks-aksclusterrg-64e0f8-uqqq0ypl.hcp.eastus.azmk8s.io:443'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true