apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-forecast
  namespace: weather-forecast-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-forecast
  template:
    metadata:
      labels:
        app: weather-forecast
    spec:
      containers:
        - name: weather-forecast
          image: sampledotnetregistery.azurecr.io/webapiserver:latest
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "dev"
          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 1
