apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-forecast-ingress
  namespace: weather-forecast-dev
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    appgw.ingress.kubernetes.io/health-probe-path: /weatherforecast
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: myweatherforecast.app.com
      http:
        paths:
        - path: /
          backend:
            service:
              name:  weather-forecast-service
              port:
                number: 80
          pathType: Exact