apiVersion: v1
kind: Service
metadata:
  name: weather-forecast-service
  namespace: weather-forecast-dev
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: weather-forecast-app