name: Display Github Secret
on:
  push:
  workflow_dispatch:

jobs:
  display-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Application variables
        id: set-application-variables
        run: |
          echo "APPLICATION_NAMES=$(yq -o=json '.' ./infra_config.yaml | jq -r '[.Applications[] | { APPLICATION_NAME: .APPLICATION_NAME, ENVIRONMENT: .ENVIRONMENT }]' | tr -d '\n')" >> $GITHUB_OUTPUT
    outputs:
      APPLICATION_NAMES: ${{ steps.set-application-variables.outputs.APPLICATION_NAMES }}

  call-reusable-workflo-matrix:
    name: Call Reusable Workflow with Matrix
    needs: display-secret
    uses: ./.github/workflows/service-principal-reusable-workflow-matrix.yaml
    strategy:
      matrix:
        APP_NAME_AND_ENV: ${{ fromJson(needs.display-secret.outputs.APPLICATION_NAMES ) }}
    with:
      application_name: ${{ matrix.APP_NAME_AND_ENV.APP_NAME }}
    secrets:
      secret_value: ${{ contains(matrix.APP_NAME_AND_ENV.ENV, 'dev') && secrets.SERVICE_PRINCIPAL_DEV || contains(matrix.APP_NAME_AND_ENV.ENV, 'np') && secrets.SERVICE_PRINCIPAL_NP || secrets.SERVICE_PRINCIPAL_PRD }}

  # call-reusable-workflo-matrix:
  #   name: Call Reusable Workflow with Matrix
  #   uses: ./.github/workflows/service-principal-reusable-workflow-matrix.yaml
  #   strategy:
  #     matrix:
  #       APP_NAME_AND_ENV:
  #         - { APP_NAME: app1, ENV: dev }
  #         - { APP_NAME: app2, ENV: np }
  #         - { APP_NAME: app3, ENV: prod }
  #   with:
  #     application_name: ${{ matrix.APP_NAME_AND_ENV.APP_NAME }}
  #   secrets:
  #     secret_value: ${{ contains(matrix.APP_NAME_AND_ENV.ENV, 'dev') && secrets.SERVICE_PRINCIPAL_DEV || contains(matrix.APP_NAME_AND_ENV.ENV, 'np') && secrets.SERVICE_PRINCIPAL_NP || secrets.SERVICE_PRINCIPAL_PRD }}
